robot_param: {
   EncoderCprLeft: 400,
   EncoderCprRight: 400,
   EncoderPosition: 0,
   Height_mm: 200,
   Lenght_mm: 365, 
   MaxAmpereMotorLeft_mA: 1650, 
   MaxAmpereMotorRight_mA: 1650, 
   MinChargedBatteryLevel_mV: 12000,
   MaxChargedBatteryLevel_mV: 16800,
   MaxRpmMotorLeft: 218, 
   MaxRpmMotorRight: 218, 
   MaxTorqueMotorLeft_Ncm: 60, 
   MaxTorqueMotorRight_Ncm: 60,
   MotorEnableLevel: 1, 
   RatioMotorLeft: 55000, 
   RatioMotorRight: 55000,
   RatioShaftLeft: 3000,
   RatioShaftRight: 3000,
   Weight_g: 5000, 
   WheelBase_mm: 340, 
   WheelRadiusLeft_cent_mm: 3500,
   WheelRadiusRight_cent_mm: 3500, 
   Width_mm: 420
}
